batch: 1
defaults:
- _self_
- llm: azure_gpt4o_mini
- agent: gaia
- environment: web_browser
exp_name: base_agent_sample
exp_path: results/base_agent
llm:
  _target_: tapeagents.llms.LiteLLM
  model_name: azure/gpt-4o-mini
  parameters:
    max_tokens: 1500
    temperature: 0.7
  stream: false
  use_cache: true
only_tasks:
- - 1
  - 0
- - 1
  - 1
- - 2
  - 0
retry_unsolved: false
split: validation
